SquirrelApp/urls.py
from django.urls import path

from . import views

app_name = 'SquirrelApp'

urlpatterns = [
        path('index', views.index, name='index'),
        path('sightings', views.sightings, name='sightings'),
        path('sightings/details/<str:sighting_id>', views.sighting_details, name='detail'),
        path('sightings/add', views.add_page, name='add_page'),
        path('sightings/stats', views.stats, name='stats'),
        path('sightings/<str:squirrel_id>', views.update_page, name='update_page'),
        path('add', views.update_request, name="add"),
        path('update', views.update_request, name="update"),
        path('map',views.map,name='map'),

        ]
       

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('SquirrelApp.urls', 'Squirrel')),
]

SquirrelApp/models.py
from django.db import models

#class Map(models.Model):
  #return "hello"


class Sighting(models.Model):

    UniqueSquirrelID=models.CharField(
            max_length=100,
            help_text='Unique Squirrel ID',
            blank=False,
            null=False,
    )

    Date=models.DateField(
            help_text='Date',
            blank=True,
            null=True,
    )

    def __str__(self):
        return f'{self.id}'


    Latitude = models.FloatField(
            max_length=20,
            help_text='Latitude',
            blank=False,
            null=False,
    )

    Longitude = models.FloatField(
            max_length=20,
            blank=False,
            null=False,
            help_text='Longitude',
    )
   
    AM = 'AM'
    PM = 'PM'

    SHIFT_CHOICES = [
            (AM, 'AM'), 
            (PM, 'PM'),
    ]

    Shift = models.CharField(
            max_length=20,
            help_text='Shift',
            choices=SHIFT_CHOICES, 
            default=AM,
            null=True,
            blank=True, 
    )

    ADULT = 'Adult'
    JUVENILE = 'Juvenile'

    AGE_CHOICES = [ (ADULT, 'Adult'), (JUVENILE, 'Juvenile'), ]

    Age = models.CharField(
            max_length=20,
            help_text='Age',
            default=ADULT,
            choices=AGE_CHOICES,
            null=True,
            blank=True,
    )

    PrimaryFurColor = models.CharField(
            max_length=20,
            blank = True,
            null=True,
            help_text="Primary Fur Color",
    )

    Location = models.TextField(
            blank = True,
            null=True,
            help_text="Location",
    )
    
    SpecificLocation = models.CharField(
            max_length=100,
            blank = True,
            null=True,
            help_text="Specific Location",
    )

    Running = models.BooleanField(
            blank=True,
            null=True,
            help_text="Running",
    )

    Chasing = models.BooleanField(
            blank=True,
            null=True,
            help_text="Chasing",
    )
    
    Climbing = models.BooleanField(
            blank=True,
            null=True,
            help_text="Climbing",
    )

    Eating = models.BooleanField(
            blank=True,
            null=True,
            help_text="Eating",
    )

    Foraging = models.BooleanField(
            blank=True,
            null=True,
            help_text="Foraging",
    )

    OtherActivities = models.CharField(
            max_length = 100,
            blank=True,
            null=True,
            help_text="Other Activities",
    )

    Kuks = models.BooleanField(
            blank=True,
            null=True,
            help_text="Kuks",
    )

    Quaas = models.BooleanField(
            blank=True,
            null=True,
            help_text="Quaas",
    )

    Moans = models.BooleanField(
            blank=True,
            null=True,
            help_text="Moans",
    )

    TailFlags = models.BooleanField(
            blank=True,
            null=True,
            help_text="Tail Flags",
    )

    TailTwitches = models.BooleanField(
            blank=True,
            null=True,
            help_text="Tail Twiches",
    )

    Approaches = models.BooleanField(
            blank=True,
            null=True,
            help_text="Approaches",
    )

    Indifferent = models.BooleanField(
            blank=True,
            null=True,
            help_text="Indifferent",
    )

    RunsFrom = models.BooleanField(
            blank=True,
            null=True,
            help_text="Runs From",
    )

    def get_fields(self):
        l = list()
        for field in Sighting._meta.fields:
            if field.name=="id":
                l.append((field.name, field.value_to_string(self)))
            else:
                l.append((field.help_text, field.value_to_string(self)))
        return l   

SquirrelApp/forms.py
from django.forms import ModelForm

from .models import Sighting


   
class SightingForm(ModelForm):
    class Meta:
        model = Sighting
        fields = [
                'UniqueSquirrelID',
                'Latitude',
                'Longitude',
                'Shift',
                'Date',
                'Age',
                'PrimaryFurColor',
                'Location',
                'SpecificLocation',
                'Running',
                'Chasing',
                'Climbing',
                'Eating',
                'Foraging',
                'OtherActivities',
                'Kuks',
                'Quaas',
                'Moans',
                'TailFlags',
                'TailTwitches',
                'Approaches',
                'Indifferent',
                'RunsFrom',
        ]

SquirrelApp/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.http import JsonResponse
from .forms import SightingForm
from .models import Sighting

def index(request):
    return render(request, 'SquirrelApp/index.html')

def sightings(request):
    sightings = Sighting.objects.all()
    context = {
            'sightings': sightings,
    }
    return render(request, 'SquirrelApp/sighting.html', context)


def sighting_details(request, sighting_id):
    sighting = get_object_or_404(Sighting, pk=sighting_id)
    return render(request, 'SquirrelApp/detail.html', {'sighting':sighting})

def update_page(request, squirrel_id):
    sighting = Sighting.objects.filter(UniqueSquirrelID=squirrel_id).order_by('id').last()
    context = {
            'sighting':sighting,
    }
    return render(request, 'SquirrelApp/update.html', context)


def update_request(request):
    if request.method == 'POST':
        form = SightingForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'SquirrelApp/submitted.html')
        else:
            return render(request, 'SquirrelApp/submitfail.html')
    else:
        return {}


def add_page(request):
    return render(request, 'SquirrelApp/add.html')

def map(request):
    sightings = Sighting.objects.all()[:100]
    context = {
            'sightings':sightings,
    }
    return render(request, 'SquirrelApp/map.html', context)

def stats(request):
    sightings=Sighting.objects.all()
    running_c=0
    chasing_c=0
    eating_c=0
    foraging_c=0
    adult_c=0
    for s in sightings:
        if s.Age == "Adult":
            adult_c+=1
        if s.Running == True:
            running_c+=1
        if s.Chasing == True:
            chasing_c+=1
        if s.Eating == True:
            eating_c+=1
        if s.Foraging == True:
            foraging_c+=1
    context={
            'AdultCounts':adult_c,
            'NumRunning':running_c,
            'NumChasing':chasing_c,
            'NumEating':eating_c,
            'NumForaging':foraging_c,
            }
    return render(request,'SquirrelApp/stats.html',context)

SquirrelApp/templates/SquirrelApp/add.html
<!DOCTYPE html>
<html>
    
<style>
input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=radio], select{
  padding= 12px 20px;
  display: inline-block;
  margin: 8px 0;
}

input[type=date], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=number], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 100%;
  background-color: #f7abbe;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #f291a9;
}

button {
  width: 100%;
  background-color: #f7abbe;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

button:hover {
  background-color: #f291a9;
}

.addLink {
  text-align: right;
}

div {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
</style>
    
<body>
  <p class="addLink"><a href="{% url 'SquirrelApp:sightings'%}">Go back to list of sightings</a></p> 
  <h3 style="color:#f291a9">Add a new sighting!</h3>
  <div>
  <p style="color:#155263">Use this form to submit a new sighting.</p>	  
  <form id="submit" method="post" action="{% url 'SquirrelApp:update' %}">
     {% csrf_token %}
       
     <label for="UniqueSquirrelID">Unique Squirrel ID</label>
     <Input type="text" id="UniqueSquirrelID" name="UniqueSquirrelID" placeholder="Unique Squirrel ID // Mandatory Field">

     <label for="Latitude">Latitude:</label>
     <input type="number" step="any" id="Latitude" placeholder="Latitude // Mandatory Field" name="Latitude">
       
     <label for="Longitude">Longitude:</label>
     <input type="number" step="any" id="Longitude" placeholder="Longitude // Mandatory Field" name="Longitude">

     <label for="Shift">Shift:</label><br>
     <input type="radio" id="AM" name="Shift" value="AM">
     <label for="AM">AM</label><br>
     <input type="radio" id="PM" name="Shift" value="PM">
     <label for="PM">PM</label><br><br>

     <label for="Date">Date:</label>
     <input type="date" id="Date" name="Date">
     
     <label for="Age">Age:</label><br>
     <input type="radio" id="Juvenile" name="Age" value="Juvenile">
     <label for="Juvenile">Juvenile</label><br>
     <input type="radio" id="Adult" name="Age" value="Adult">
     <label for="Adult">Adult</label><br><br>

     <label for="PrimaryFurColor">Primary Fur Color:</label>
     <Input type="text" id="PrimaryFurColor" name="PrimaryFurColor" placeholder="Primary Fur Color"> 
         
     <label for="Location">Location:</label>
     <Input type="text" id="Location" name="Location" placeholder="Location"> 
     
     <label for="SpecificLocation">Specific Location:</label>
     <Input type="text" id="SpecificLocation" name="SpecificLocation" placeholder="Specific Location"> 
         
     <label for="Running">Running:</label><br>
     <input type="radio" id="True" name="Running" value="True">
     <label for="True">True</label><br>
     <input type="radio" id="False" name="Running" value="False">
     <label for="False">False</label><br><br>


     <label for="Chasing">Chasing:</label><br>
     <input type="radio" id="True" name="Chasing" value="True">
     <label for="True">True</label><br>
     <input type="radio" id="False" name="Chasing" value="False">
     <label for="False">False</label><br><br>

     <label for="Climbing">Climbing: </label><br>
     <input type="radio" id="True" name="Climbing" value="True">
     <label for="True">True</label><br>
     <input type="radio" id="False" name="Climbing" value="False">
     <label for="False">False</label><br><br>         
     
     <label for="Eating">Eating: </label><br>
     <input type="radio" id="True" name="Eating" value="True">
     <label for="True">True</label><br>
     <input type="radio" id="False" name="Eating" value="False">
     <label for="False">False</label><br><br>    
     
     <label for="Foraging">Foraging: </label><br>
     <input type="radio" id="True" name="Foraging" value="True">
     <label for="True">True</label><br>
     <input type="radio" id="False" name="Foraging" value="False">
     <label for="False">False</label><br><br>

     <label for="OtherActivities">Other Activities:</label>
     <Input type="text" id="OtherActivities" name="OtherActivities" placeholder="Other Activities"> 

     <label for="Kuks">Kuks: </label><br>
     <input type="radio" id="True" name="Kuks" value="True">
     <label for="True">True</label><br>
     <input type="radio" id="False" name="Kuks" value="False">
     <label for="False">False</label><br><br>

     <label for="Quaas">Quaas: </label><br>
     <input type="radio" id="True" name="Quaas" value="True">
     <label for="True">True</label><br>
     <input type="radio" id="False" name="Quaas" value="False">
     <label for="False">False</label><br><br>
        
     <label for="Moans">Moans: </label><br>
     <input type="radio" id="True" name="Moans" value="True">
     <label for="True">True</label><br>
     <input type="radio" id="False" name="Moans" value="False">
     <label for="False">False</label><br><br>
        
     <label for="TailFlags">Tail Flags: </label><br>
     <input type="radio" id="True" name="TailFlags" value="True">
     <label for="True">True</label><br>
     <input type="radio" id="False" name="TailFlags" value="False">
     <label for="False">False</label><br><br>
        
     <label for="TailTwitches">Tail Twitches: </label><br>
     <input type="radio" id="True" name="TailTwitches" value="True">
     <label for="True">True</label><br>
     <input type="radio" id="False" name="TailTwitches" value="False">
     <label for="False">False</label><br><br>
        
     <label for="Approaches">Approaches: </label><br>
     <input type="radio" id="True" name="Approaches" value="True">
     <label for="True">True</label><br>
     <input type="radio" id="False" name="Approaches" value="False">
     <label for="False">False</label><br><br>
        
     <label for="Indifferent">Indifferent: </label><br>
     <input type="radio" id="True" name="Indifferent" value="True">
     <label for="True">True</label><br>
     <input type="radio" id="False" name="Indifferent" value="False">
     <label for="False">False</label><br><br>
        
     <label for="RunsFrom">RunsFrom: </label><br>
     <input type="radio" id="True" name="RunsFrom" value="True">
     <label for="True">True</label><br>
     <input type="radio" id="False" name="RunsFrom" value="False">
     <label for="False">False</label><br><br>         
         
     <button type="button" onclick="validate()">Validate input before you submit!</button>   
     <input type="submit" value="Add">
     <p id="error_msg" style="color:red"></p>
    
  </form>
  </div>
</body>


<script>
function validate(){
  var lat, lon, sqid,  message;
  message = document.getElementById("error_msg");
  message.innerHTML = "";
  lat = document.getElementById("Latitude").value;
  lon = document.getElementById("Longitude").value;
  sqid = document.getElementById("UniqueSquirrelID").value;
  try{
    if (lat=="" || lon=="") throw "Error: Latitude/Longitude is empty!";
    if (sqid == "") throw "Error: Unique Squirrel ID is empty!"
  }
  catch(err){
    message.innerHTML = err;
  }
  finally{
    message.innerHTML = message.innerHTML + " Validation complete."
  }
}

</script>







</html>

SquirrelApp/templates/SquirrelApp/detail.html
<!doctype html>
<html>
  <head>
    <h3 style="color:#e6739f">Details for sigthting {{sighting.id}}</h5>
  </head>
  <body>
  <div>
    <ul>
    {% for name, value in sighting.get_fields %}
      <li>{{name}}: {{value}}</li>
    {% endfor %}
    </ul>
  </div>
  <a href="{% url 'SquirrelApp:sightings' %}">Go back to list of sightings</a>
  </body>
</html> 

SquirrelApp/templates/SquirrelApp/index.html
<!doctype html>
<html>
<head>
<style>
h1 {text-align: center;}
div {text-align: center}
a:link, a:visited {
  border: 2px solid #ffebef;
  background-color: white; 
  color: #e6739f;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
}

a:hover, a:active {
  color: white;
  background-color: #ffb8c9;
}

</style>
</head>

<body>
<h1 style="color:#e6739f">TRACK THAT SQUIRREL DOWN!</h1>
<div>
<a href="{% url 'SquirrelApp:map' %}">Map</a>
<a href="{% url 'SquirrelApp:sightings' %}">Sightings</a>
</div>
</body>

</html>

SquirrelApp/templates/SquirrelApp/map.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet"
          href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
            integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
            crossorigin=""></script>

    <style>
      html,body {
        height: 100%;
      }
    </style>
  </head>
  <body>
    <div id="map" class="container-fluid h-100"></div>
    <div>Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Leaflet JS -->
    <script>
        var map_center = [
            40.782091,  // Latitude
            -73.964285  // Longitude
        ];
        var zoom_level = 14;
        var map = L.map('map').setView(map_center, zoom_level);
        L.tileLayer('https://{server}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            server: 'a',  // can be 'a', 'b', or 'c'
            // must leave attribution in!
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>',
        }).addTo(map);
        
        <!-- L.Icon.Default.prototype.options.iconSize = 15; -->
        <!-- L.Icon.Default.prototype.options.iconAnchor = [0, 0]; -->
        <!-- L.Icon.Default.prototype.options.shadowSize = 15; -->
        <!-- L.Icon.Default.prototype.options.shadowAnchor = [0, 0]; -->

	{% for s in sightings %}
	  var point_lat_lon = [{{ s.Longitude }}, {{ s.Latitude }}];
	  var marker = L.marker(point_lat_lon).addTo(map);
        {% endfor %}
    </script>
  </body>
</html>

SquirrelApp/templates/SquirrelApp/sighting.html
<!DOCTYPE html>
<html>
<head>
<style>
table, th, td {
  border: 1px solid black;
}
.addLink {
  text-align: right;
}
</style>
</head>
<body>
<div class="addLink">
  <a href="{% url 'SquirrelApp:add_page' %}">Add New Sightings!</a>
</div>
<div class="addLink">
  <a href="{% url 'SquirrelApp:stats' %}">View Sighting Statistics!</a>
</div>
<div class="addLink">
  <a href="{% url 'SquirrelApp:index' %}">Go Back to Index Page!</a>
</div>


<h1 style="color:#e6739f">Sightings</h1>

<div class="table, th, td">
<table>
  <tr>
    <th> Sighting ID </th>
    <th> Unique Squirrel ID </th>
    <th> Date </th>
    <th> View Sighting Details </th>
    <th> Update Sighting </th>
  </tr>
  {% for sighting in sightings %}
    
  <tr>
    <td>{{sighting.id}}</td>
    <td>{{sighting.UniqueSquirrelID}}</td>
    <td>{{sighting.Date}}</td>
    <td><a href="{% url 'SquirrelApp:detail' sighting.id %}">Detail</a></td>
    <td><a href="{% url 'SquirrelApp:update_page' sighting.UniqueSquirrelID %}">Update</a></td>
  </tr>
  {% endfor %}
</table>
</div>

</body>
</html>

SquirrelApp/templates/SquirrelApp/stats.html
<!doctype html>
<html>
   <body>
      <h3 style="color:#e6739f">Some Stats About Our Squirrels!</h3>
      <ul>
		<li>The number of adult squirrels is {{AdultCounts}}.</li>
		<li>Total of {{NumRunning}} squirrels were running.</li>
		<li>Total of {{NumEating}} squirrels were eating.</li>
		<li>Total of {{NumChasing}} squirrels were chasing.</li>
		<li>Total of {{NumForaging}} squirrels were foraing.</li>
      </ul>

      <p><a href="{% url 'SquirrelApp:sightings' %}">Go back to list of sightings</a></p>
  </body>
</html> 
	

SquirrelApp/templates/SquirrelApp/submitfail.html
<!doctype html>
<html>
<body>
	<strong>Submission failed! Please make sure you fill in all mandatory fields and use the "Validation" button to check your input!</strong><br>
	<a href="{% url "SquirrelApp:sightings" %}">Go back to list of sightings</a>
</body>
</html>

SquirrelApp/templates/SquirrelApp/submitted.html
<!doctype html>
<html>
<body>
  <strong>Submitted!</strong><br>
  <a href="{% url 'SquirrelApp:sightings' %}">Go back to list of sightings</a>
</body>
</html>

SquirrelApp/templates/SquirrelApp/update.html
<!DOCTYPE html>

<html>

<style>
input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=date], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=radio], select{
  padding= 12px 20px;
  display: inline-block;
  margin: 8px 0;
}

input[type=number], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}


input[type=submit] {
  width: 100%;
  background-color: #f7abbe;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #f291a9;
}

button{
  width: 100%;
  background-color: #f7abbe;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

button:hover {
  background-color: #f291a9;
}


.addLink {
  text-align: right;
}

div {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
</style>

<body>
   <p class="addLink"><a href="{% url 'SquirrelApp:sightings'%}">Go back to list of sightings</a></p>
   <h3 style="color:#e6739f">Update Form for Squirrel {{ sighting.UniqueSquirrelID }}</h3>
   <div>
   <p style="color:#155263">Use this form to update a sighting for squirrel {{ sighting.UniqueSquirrelID }}. This form is prepopulated with the lat/long and date of the lastest sighting of squirrel {{ sighting.UniqueSquirrelID }}.</p>
   
   <form id="submit" method="post" action="{% url 'SquirrelApp:update' %}">
        {% csrf_token %}
	<label for="Latitude">Latitude:</label>
	<input type="number" step="any" id="Latitude" value="{{sighting.Latitude}}" placeholder="Latitude // Mandatory Field" name="Latitude">

        <label for="Longitude">Longitude:</label>
        <input type="number" step="any" id="Longitude" value="{{sighting.Longitude}}" placeholder="Longitude // Mandatory Field" name="Longitude">

        <label for="Shift">Shift:</label><br>
	<input type="radio" id="AM" name="Shift" value="AM" >
        <label for="AM">AM</label><br>
        <input type="radio" id="PM" name="Shift" value="PM" >
	<label for="PM">PM</label><br><br>

        <label for="Date">Date:</label>
        <input type="date" id="Date" value="{{sighting.Date|date:"Y-m-d"}}" name="Date">
        
	<label for="Age">Age:</label><br>
        <input type="radio" id="Juvenile" name="Age" value="Juvenile">
        <label for="Juvenile">Juvenile</label><br>
        <input type="radio" id="Adult" name="Age" value="Adult">
        <label for="Adult">Adult</label><br><br>

	<input type="hidden" id="UniqueSquirrelID" name="UniqueSquirrelID" value="{{sighting.UniqueSquirrelID}}">
	<button type="button" onclick="validate()">Validate Input before you submit!</button>
	<input type="submit" value="Update">
	<p id="error_msg" style="color:red"></p>
    </form>
    </div>
</body>

<script>
function validate(){
  var lat, lon, message;
  message = document.getElementById("error_msg");
  message.innerHTML = "";
  lat = document.getElementById("Latitude").value;
  lon = document.getElementById("Longitude").value;
  try{
    if (lat=="" || lon=="") throw "empty";
    if (isNaN(lat) || isNaN(lon)) throw "not a number";
  }
  catch(err){
    message.innerHTML = "Error: Latitude/Longitude is " + err + ".";
  }
  finally{
    message.innerHTML = message.innerHTML + " Validation complete."
  }
}

</script>



</html>